name: Generate Repo Diagram
on: [push]
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "diagram.svg"
          excluded_paths: "node_modules, .env"
      - name: Commit diagram
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add diagram.svg
          git commit -m "Update repo diagram"
          git push
